#!/usr/bin/env python3
"""Generate IconCodepoints.swift from the icon names the app uses.

Material Symbols ships as a codepoint font with no ligature table, so
Text("electric_scooter") renders the literal word instead of the glyph. Names are
resolved against the font's cmap here.

Icon names reach the Icon view two ways: inline, and as a string parameter passed
down to a row builder. Scanning only for Icon("...") misses the second kind, so
every snake_case literal in the sources is intersected with the font's glyph
names. A literal that happens to match a real glyph name and is not an icon costs
one unused dictionary entry, which is cheaper than a missing icon.
"""
import re, sys, pathlib
from fontTools.ttLib import TTFont

root = pathlib.Path(__file__).resolve().parent.parent
font = TTFont(root / "KQiRides/Resources/MaterialSymbolsSharp.ttf")
rev = {}
for cp, g in font.getBestCmap().items():
    rev.setdefault(g, cp)

names, direct = set(), set()
for f in (root / "KQiRides/Sources").glob("*.swift"):
    if f.name == "IconCodepoints.swift":
        continue
    text = f.read_text()
    direct |= set(re.findall(r'Icon\("([a-z0-9_]+)"', text))
    for lit in re.findall(r'"([a-z][a-z0-9_]{2,})"', text):
        if lit in rev:
            names.add(lit)

# A name written straight into Icon() must exist; that is a typo, not a coincidence.
missing = sorted(n for n in direct if n not in rev)
if missing:
    sys.exit("icon names not in the font: " + ", ".join(missing))
names |= direct

lines = ["// Generated by scripts/make-icon-map.py. Do not edit.",
         "enum IconGlyph {",
         "    static let map: [String: String] = ["]
for n in sorted(names):
    lines.append(f'        "{n}": "\\u{{{rev[n]:X}}}",')
lines += ["    ]", "}", ""]
(root / "KQiRides/Sources/IconCodepoints.swift").write_text("\n".join(lines))
print(f"mapped {len(names)} icons")
